---
- name: Push container images to ACR registry
  hosts: localhost
  become: true
  vars:
    acr_name: "jgjcp2acr.azurecr.io"
    acr_username: "jgjcp2acr"
  tasks:
    - name: Ensure Podman is installed
      ansible.builtin.apt:
        name: podman
        update_cache: yes
        state: present

    - name: Login to ACR
      containers.podman.podman_login:
        registry: "{{ acr_name }}"
        username: "{{ acr_username }}"
        password: "{{ acr_password }}"

    - name: Pull Nginx image
      containers.podman.podman_image:
        name: "docker.io/nginx"

    - name: Pull Redis image
      containers.podman.podman_image:
        name: "mcr.microsoft.com/oss/bitnami/redis"
        tag: "6.0.8"

    - name: Pull Azure-vote-front image
      containers.podman.podman_image:
        name: "mcr.microsoft.com/azuredocs/azure-vote-front"
        tag: "v1"

    - name: Push Nginx image to ACR
      containers.podman.podman_image:
        name: "{{ acr_name }}/nginx/nginx"
        tag: "casopractico2"
        push: yes

    - name: Push Redis image to ACR
      containers.podman.podman_image:
        name: "{{ acr_name }}/redis/redis"
        tag: "casopractico2"
        push: yes

    - name: Push Azure-vote-front image to ACR
      containers.podman.podman_image:
        name: "{{ acr_name }}/front/azure-vote-front"
        tag: "casopractico2"
        push: yes

